FROM quay.io/soketi/soketi:1.5.0-16-debian

ARG SOKETI_DEFAULT_APP_ID
ENV SOKETI_DEFAULT_APP_ID=$SOKETI_DEFAULT_APP_ID

ARG SOKETI_DEFAULT_APP_KEY
ENV SOKETI_DEFAULT_APP_KEY=$SOKETI_DEFAULT_APP_KEY

ARG SOKETI_DEFAULT_APP_SECRET
ENV SOKETI_DEFAULT_APP_SECRET=$SOKETI_DEFAULT_APP_SECRET

ENV SOKETI_HOST=0.0.0.0

ENV USER_AUTHENTICATION_TIMEOUT=5000
ENV DEFAULT_APP_USER_AUTHENTICATION=true
ENV SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true
ENV SOKETI_DEFAULT_APP_MAX_CLIENT_EVENTS_PER_SEC=1
